<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "student.dtd">-->

<!DOCTYPE students [

		<!ELEMENT students (student+) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>


		]>

<students>
	<student number="s001">
		<name>Lucy</name>
		<age>23</age>
		<sex>female</sex>
	</student>

	<student number="s002">
		<name>黎明</name>
		<age>33</age>
		<sex>male</sex>
	</student>
</students>